
version: 2
jobs:
  build-job:
    docker:
      - image: forrestbthomas/blog
    working_directory: /blog
    steps:
      - run: echo `which aws`
      - run: git pull origin master
      - run: pwd && ls /blog
      - run: echo $AWS_ACCESS_KEY_ID && echo $AWS_SECRET_ACCESS_KEY
            
  deploy-job:
    docker:
      - image: forrestbthomas/blog
    working_directory: /blog
    steps:
      - run:
          name: Deploy if tests pass and branch is Master
          command: aws s3 cp /index.html s3://forrestbthomas.com/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
            
