
version: 2
jobs:
  build-job:
    docker:
      - image: forrestbthomas/blog
    working_directory: /tmp/my-project
    steps:
      - run: echo "awscli exists..."
      - run: echo `which aws`
            
  deploy-job:
    docker:
      - image: forrestbthomas/blog
    working_directory: /tmp/my-project  
    steps:
      - run:
          name: Deploy if tests pass and branch is Master
          command: aws s3 sync index.html s3://forrestbthomas.com/index.html --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
            
