version: 2
jobs:
  build-job:
    docker:
      - { image: forrestbthomas/blog }
    working_directory: /blog
    steps:
      - { run: 'echo `which aws`' }
      - { run: 'pwd && ls ./' }
      - { run: 'git pull origin $CIRCLE_BRANCH' }
      - { run: 'ls ./server' }
  deploy-job:
    docker:
      - { image: forrestbthomas/blog }
    working_directory: /blog
    steps:
      - { run: { name: 'Pull latest', command: 'git pull origin master' } }
      - { run: { name: 'Build index.html', command: 'node ./server/inject-html.js' } }
      - { run: { name: 'Deploy index.html if tests pass and branch is Master', command: 'aws s3 cp /blog/index.html s3://forrestbthomas.com/ --acl public-read' } }
      - { run: { name: 'Deploy scripts/ if tests pass and branch is Master', command: 'aws s3 cp /blog/scripts s3://forrestbthomas.com/scripts --recursive --acl public-read' } }
      - { run: { name: 'Deploy archive/index.html if tests pass and branch is Master', command: 'aws s3 cp /blog/archive/index.html s3://forrestbthomas.com/archive/index.html --acl public-read' } }
      - { run: { name: 'Deploy images/ if tests pass and branch is Master', command: 'aws s3 cp /blog/images s3://forrestbthomas.com/archive --recursive --acl public-read' } }
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - { deploy-job: { requires: [build-job], filters: { branches: { only: master } } } }
